// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: calculator.proto

package server

import (
	"context"

	"repaycal/apps/calculator/rpc/internal/logic"
	"repaycal/apps/calculator/rpc/internal/svc"
	"repaycal/apps/calculator/rpc/protoc/calculator"
)

type CalculateServer struct {
	svcCtx *svc.ServiceContext
	calculator.UnimplementedCalculateServer
}

func NewCalculateServer(svcCtx *svc.ServiceContext) *CalculateServer {
	return &CalculateServer{
		svcCtx: svcCtx,
	}
}

func (s *CalculateServer) CalculatePMT(ctx context.Context, in *calculator.PMTRequest) (*calculator.PMTResponse, error) {
	l := logic.NewCalculatePMTLogic(ctx, s.svcCtx)
	return l.CalculatePMT(in)
}
