apiVersion: v1
kind: Service
metadata:
  name: etcd  # 👈 名字直接叫 etcd
spec:
  ports:
    - port: 2379
      name: client
  selector:
    app: etcd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.12
          env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_ENABLE_V2
              value: "true"
            - name: ETCD_LISTEN_CLIENT_URLS
              value: "http://0.0.0.0:2379"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://etcd:2379" # 👈 对应 Service 名字
          ports:
            - containerPort: 2379
              name: client