apiVersion: v1
kind: Service
metadata:
  name: calculator
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: calculator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      initContainers:
        # 👈 阻塞等待无后缀的 etcd 和 postgres 端口开放
        - name: wait-for-etcd
          image: alpine:latest
          command: ["sh", "-c", "until nc -z -v -w3 etcd 2379; do echo 'Waiting for etcd...'; sleep 2; done;"]
        - name: wait-for-postgres
          image: alpine:latest
          command: ["sh", "-c", "until nc -z -v -w3 postgres 5432; do echo 'Waiting for Postgres...'; sleep 2; done;"]
      containers:
        - name: calculator
          image: repaycal-calculator-rpc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080