// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package pmtlog

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pmtLogFieldNames          = builder.RawFieldNames(&PmtLog{}, true)
	pmtLogRows                = strings.Join(pmtLogFieldNames, ",")
	pmtLogRowsExpectAutoSet   = strings.Join(stringx.Remove(pmtLogFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	pmtLogRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(pmtLogFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	pmtLogModel interface {
		Insert(ctx context.Context, data *PmtLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PmtLog, error)
		Update(ctx context.Context, data *PmtLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPmtLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PmtLog struct {
		Id               int64     `db:"id"`
		LoanAmount       int64     `db:"loan_amount"`
		InterestRate     int64     `db:"interest_rate"`
		NumberOfPayments int64     `db:"number_of_payments"`
		MonthlyRepayment int64     `db:"monthly_repayment"`
		CreatedAt        time.Time `db:"created_at"`
	}
)

func newPmtLogModel(conn sqlx.SqlConn) *defaultPmtLogModel {
	return &defaultPmtLogModel{
		conn:  conn,
		table: `"public"."pmt_log"`,
	}
}

func (m *defaultPmtLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPmtLogModel) FindOne(ctx context.Context, id int64) (*PmtLog, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", pmtLogRows, m.table)
	var resp PmtLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPmtLogModel) Insert(ctx context.Context, data *PmtLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, pmtLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LoanAmount, data.InterestRate, data.NumberOfPayments, data.MonthlyRepayment)
	return ret, err
}

func (m *defaultPmtLogModel) Update(ctx context.Context, data *PmtLog) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, pmtLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.LoanAmount, data.InterestRate, data.NumberOfPayments, data.MonthlyRepayment)
	return err
}

func (m *defaultPmtLogModel) tableName() string {
	return m.table
}
