// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: calculator.proto

package calculate

import (
	"context"

	"repaycal/apps/calculator/rpc/protoc/calculator"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PMTRequest  = calculator.PMTRequest
	PMTResponse = calculator.PMTResponse

	Calculate interface {
		CalculatePMT(ctx context.Context, in *PMTRequest, opts ...grpc.CallOption) (*PMTResponse, error)
	}

	defaultCalculate struct {
		cli zrpc.Client
	}
)

func NewCalculate(cli zrpc.Client) Calculate {
	return &defaultCalculate{
		cli: cli,
	}
}

func (m *defaultCalculate) CalculatePMT(ctx context.Context, in *PMTRequest, opts ...grpc.CallOption) (*PMTResponse, error) {
	client := calculator.NewCalculateClient(m.cli.Conn())
	return client.CalculatePMT(ctx, in, opts...)
}
