// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: calculator.proto

package calculator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PMTRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LoanAmount       int64                  `protobuf:"varint,1,opt,name=loan_amount,json=loanAmount,proto3" json:"loan_amount,omitempty"`
	InterestRate     int32                  `protobuf:"varint,2,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	NumberOfPayments int32                  `protobuf:"varint,3,opt,name=number_of_payments,json=numberOfPayments,proto3" json:"number_of_payments,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PMTRequest) Reset() {
	*x = PMTRequest{}
	mi := &file_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PMTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PMTRequest) ProtoMessage() {}

func (x *PMTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PMTRequest.ProtoReflect.Descriptor instead.
func (*PMTRequest) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *PMTRequest) GetLoanAmount() int64 {
	if x != nil {
		return x.LoanAmount
	}
	return 0
}

func (x *PMTRequest) GetInterestRate() int32 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *PMTRequest) GetNumberOfPayments() int32 {
	if x != nil {
		return x.NumberOfPayments
	}
	return 0
}

type PMTResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MonthlyRepayment int64                  `protobuf:"varint,1,opt,name=monthly_repayment,json=monthlyRepayment,proto3" json:"monthly_repayment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PMTResponse) Reset() {
	*x = PMTResponse{}
	mi := &file_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PMTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PMTResponse) ProtoMessage() {}

func (x *PMTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PMTResponse.ProtoReflect.Descriptor instead.
func (*PMTResponse) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *PMTResponse) GetMonthlyRepayment() int64 {
	if x != nil {
		return x.MonthlyRepayment
	}
	return 0
}

var File_calculator_proto protoreflect.FileDescriptor

const file_calculator_proto_rawDesc = "" +
	"\n" +
	"\x10calculator.proto\x12\n" +
	"calculator\"\x80\x01\n" +
	"\n" +
	"PMTRequest\x12\x1f\n" +
	"\vloan_amount\x18\x01 \x01(\x03R\n" +
	"loanAmount\x12#\n" +
	"\rinterest_rate\x18\x02 \x01(\x05R\finterestRate\x12,\n" +
	"\x12number_of_payments\x18\x03 \x01(\x05R\x10numberOfPayments\":\n" +
	"\vPMTResponse\x12+\n" +
	"\x11monthly_repayment\x18\x01 \x01(\x03R\x10monthlyRepayment2L\n" +
	"\tCalculate\x12?\n" +
	"\fcalculatePMT\x12\x16.calculator.PMTRequest\x1a\x17.calculator.PMTResponseB\x0eZ\f./calculatorb\x06proto3"

var (
	file_calculator_proto_rawDescOnce sync.Once
	file_calculator_proto_rawDescData []byte
)

func file_calculator_proto_rawDescGZIP() []byte {
	file_calculator_proto_rawDescOnce.Do(func() {
		file_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)))
	})
	return file_calculator_proto_rawDescData
}

var file_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_calculator_proto_goTypes = []any{
	(*PMTRequest)(nil),  // 0: calculator.PMTRequest
	(*PMTResponse)(nil), // 1: calculator.PMTResponse
}
var file_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.Calculate.calculatePMT:input_type -> calculator.PMTRequest
	1, // 1: calculator.Calculate.calculatePMT:output_type -> calculator.PMTResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_proto_init() }
func file_calculator_proto_init() {
	if File_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_proto_depIdxs,
		MessageInfos:      file_calculator_proto_msgTypes,
	}.Build()
	File_calculator_proto = out.File
	file_calculator_proto_goTypes = nil
	file_calculator_proto_depIdxs = nil
}
